export const COMPLETION_PERFORMANCE_TYPES = {
  EARLY: "Early",
  ON_TIME: "On Time",
  LATE: "Late",
};

export const INITIAL_TASKS = [
  {
    id: "task-1",
    title: "Design System & UI Tokens",
    description: "Create standard color palette, typography scale, and reusable UI tokens for the Kanban board application.",
    category: "Design",
    startDate: "2026-08-01",
    dueDate: "2026-08-10",
    completeDate: "2026-08-08",
    responsiblePerson: {
      id: "person-2",
      name: "Alice Smith",
      avatar: "AS",
    },
    status: "done",
  },
  {
    id: "task-2",
    title: "Setup React Router & Page Shells",
    description: "Configure client-side routing between Kanban Board and Dashboard Overview pages.",
    category: "Development",
    startDate: "2026-08-05",
    dueDate: "2026-08-12",
    completeDate: "2026-08-12",
    responsiblePerson: {
      id: "person-1",
      name: "John Doe",
      avatar: "JD",
    },
    status: "done",
  },
  {
    id: "task-3",
    title: "Kanban Board Drag & Drop",
    description: "Implement interactive drag and drop functionality for moving cards across TO DO, DOING, and DONE columns.",
    category: "Development",
    startDate: "2026-08-10",
    dueDate: "2026-08-18",
    completeDate: null,
    responsiblePerson: {
      id: "person-1",
      name: "John Doe",
      avatar: "JD",
    },
    status: "doing",
  },
  {
    id: "task-4",
    title: "User Requirements & PRD Sync",
    description: "Gather feedback from stakeholders regarding task status tracking and summary dashboard metric counts.",
    category: "Research",
    startDate: "2026-08-02",
    dueDate: "2026-08-07",
    completeDate: "2026-08-09",
    responsiblePerson: {
      id: "person-4",
      name: "Emma Watson",
      avatar: "EW",
    },
    status: "done",
  },
  {
    id: "task-5",
    title: "Local Storage Data Persistence",
    description: "Implement local storage state sync for tasks, categories, and responsible person updates.",
    category: "Development",
    startDate: "2026-08-08",
    dueDate: "2026-08-11",
    completeDate: null,
    responsiblePerson: {
      id: "person-3",
      name: "Bob Johnson",
      avatar: "BJ",
    },
    status: "doing",
  },
  {
    id: "task-6",
    title: "Dashboard Overview Charts",
    description: "Integrate Status Doughnut Chart, Category Bar Chart, and Completion Performance chart on the dashboard.",
    category: "Development",
    startDate: "2026-08-14",
    dueDate: "2026-08-20",
    completeDate: null,
    responsiblePerson: {
      id: "person-1",
      name: "John Doe",
      avatar: "JD",
    },
    status: "todo",
  },
  {
    id: "task-7",
    title: "End-to-End Test Suite",
    description: "Write automated tests for task creation, editing, status changes, and filter operations.",
    category: "Testing",
    startDate: "2026-08-16",
    dueDate: "2026-08-22",
    completeDate: null,
    responsiblePerson: {
      id: "person-5",
      name: "Michael Chen",
      avatar: "MC",
    },
    status: "todo",
  },
  {
    id: "task-8",
    title: "Release Documentation & Deployment",
    description: "Document user guide, API references, and build scripts for gh-pages deployment.",
    category: "Documentation",
    startDate: "2026-08-18",
    dueDate: "2026-08-25",
    completeDate: null,
    responsiblePerson: {
      id: "person-4",
      name: "Emma Watson",
      avatar: "EW",
    },
    status: "todo",
  },
];
